FROM python:3.10.11

# Update and install required packages
RUN apt update && apt install \
        git \
        curl \
        -y

# Install pyenv
RUN curl https://pyenv.run | bash

# Set environment variables for pyenv
ENV HOME /root
ENV PYENV_ROOT $HOME/.pyenv
ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH

# Initialize pyenv
RUN eval "$(pyenv init --path)"

# Install Python 3.10.11 using pyenv and set it as global
RUN pyenv install 3.10.11 && pyenv global 3.10.11

# Install Poetry
RUN pip install poetry==1.6.1

# Verify installations
RUN python --version
RUN poetry --version

# Set the working directory
WORKDIR /app

# Copy the application code to the container
COPY . /app

# Install Python dependencies using Poetry
RUN poetry install --no-dev --no-root

# Expose the port the frontend runs on
EXPOSE 8501

# Run the frontend service
CMD ["streamlit", "run", "rnaseq_viz/frontend/main.py"]
